// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "goframe2-skeleton/internal/logic/middleware"
	_ "goframe2-skeleton/internal/logic/user"
)
