// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	user "goframe2-skeleton/api/v1"
	"goframe2-skeleton/internal/model/entity"
)

type (
	IUser interface {
		Login(ctx context.Context, req *user.LoginDoReq) (user *entity.AiUser, err error)
		UserInfoPublic(ctx context.Context, userId int) (data *user.GetUserInfoRes, err error)
		GetInfo(ctx context.Context, userId int) (data *user.GetUserInfoRes, err error)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
