// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe2-skeleton/internal/dao/internal"
)

// internalAiUserDao is internal type for wrapping internal DAO implements.
type internalAiUserDao = *internal.AiUserDao

// aiUserDao is the data access object for table ai_user.
// You can define custom methods on it to extend its functionality as you wish.
type aiUserDao struct {
	internalAiUserDao
}

var (
	// AiUser is globally public accessible object for table ai_user operations.
	AiUser = aiUserDao{
		internal.NewAiUserDao(),
	}
)

// Fill with you ideas below.
